spring.application.name=conta-bancaria
# Configura��es do banco de dados H2
spring.datasource.url=jdbc:h2:mem:conta-bancaria-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# Configura��es do H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ===============================
# Configura��o JWT (exemplo)
# ===============================
# ${JWT_SECRET}
security.jwt.secret=mysupersecretkeymysupersecretkey123!
# 60*15 // 15 minutos
security.jwt.access-expiration= 900
# 60*60*24*7 // 7 dias
security.jwt.refresh-expiration= 604800

server.address=0.0.0.0
server.port=8080

# ===============================
# Configura��o do Admin Provis�rio
# ===============================
sistema.admin.email=admin@senai.com
sistema.admin.senha=admin123